{% set author = "lloyd" %}
{% set name = "yajl" %}
{% set version = "0.3.5" %}
{% set sha256sum = "d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ author }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  features:
    - vc9   # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake 3.*
    - python     # [win]
    - vc 9       # [win and py27]
    - vc 10      # [win and py34]
    - vc 14      # [win and py>=35]

  run:
    - vc 9       # [win and py27]
    - vc 10      # [win and py34]
    - vc 14      # [win and py>=35]

test:
  requires:
    - pkg-config  # [unix]

  commands:
    - echo "{}" | json_reformat  # [unix]
    - echo "{}" | json_verify  # [unix]

    - test -f ${PREFIX}/include/{{ name }}/{{ name }}_common.h  # [unix]
    - test -f ${PREFIX}/lib/lib{{ name }}_s.a  # [unix]
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so  # [linux]
    - pkg-config --cflags --libs {{ name }}  # [unix]

    - if not exist %PREFIX%\\Library\\include\\{{name }}\\{{ name }}_common.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\{{ name }}_s.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\{{ name }}.dll exit 1  # [win]

    - conda inspect linkages -p $PREFIX {{ name }}  # [unix]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]

about:
  home: https://lloyd.github.io/yajl/
  license: ISC
  license_file: COPYING
  summary: Yet Another JSON Library
  description: |
    YAJL is a small event-driven (SAX-style) JSON parser written in ANSI C, and
    a small validating JSON generator. YAJL is released under the ISC license.
  dev_url: https://github.com/lloyd/yajl

extra:
  recipe-maintainers:
    - rmax
