# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ncoAxejTpovmqUrr1trdHa0gq53O7CBzGTqmMy0EoXCdjJmm5c/dJ4f4sn1l4w1uXbeOPsG6UG60tTuZbSlug/dn4tNFQkNvIhFHi9I53XwaGivXmUpCs+g9nTPZKJDEkWk0jos0c6DYewZ0TjLS0U7nTKKWWEN4G30otx+og0fbsauH8Ss3vH9nlMgbYihxz5ouhUOQ4GUA8pax6O8CzvB4fgm1G1jE+DqVkjyGs+8g6qn529TmkhmirFcAX6CBhiq4+mQnwt80Xa+DWQGHDqg2sHXrBwzsP1PVkreBx+KUAS7G8aqsZiGo0fKhxXzceBBi/s3xeyxly+UcVBpZwpsTPZ/HkWIGP18FFTYeJ5YgtLTy2HnpunJx126iyz7MHh6IhVLZQ3lON4rwvfaguZjPoqgqiDUSHeDq5fLI5uSXmnFLQIgNqhIrtdmWvdDt7tJmpitJ6ElHAWCKHcyDB4c/EjxKGDuYpnWJLAi70PNWB7XErdGpTe9iu5/MjwPZ8UmYB0+cOlKC/Q91En9kVzWzI41l9Yn0oyF4lZNHqe0dNAUuHAu0F1k98VoD7co+6gz5quSpwEaHh9r9YamTkO6jFbNsi64DjR3HX7anxP4if/E2TMOflyfHvSGQfpa2hrAzgvFGlWWDYyrXnPiWKIQc2Kg5tZULlHbyhZVyKGk="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
