travis:
  secure:
    BINSTAR_TOKEN: GPeCAJb1A5gusuklHRX+P4sYi63aD9h5VcAvZHd3oVQsZgbDIwMryrUSJ1QND5TJmAFDkyUOuIri8RceUiyUlwU72OURMnwZM43uHmbv5XB+e8Bc2jQFewbpkWH09FR5yXFDXNWwpotieQ6mR3nUisDrkkyluXzAmygNvpbIjbo/VdE+WcE9u8sHigqPjfsc/aCBWBMl3F9nrfr5+ifwXX50/vhu1Yuu7q3JIGf3phLhfyyLSm7lH6E+dTUcydZE/1LgW2uWSvvyOKjzC04x8g9qsnBttgrZUCzGgdhOa9IsDnPOlU7MI9ULO5IM7nmbIanG7FXk2dkTXo75nM2bVRqxJI/L7EUiQ/2477NVCkQ7N0hoqLCVHvw+LPl59JQIZMazzffXLn/l/ImnGbBiS6NDzuHN7REkpiBawvqFAvVyGBvA9PHCjz1D1y45GgxkQjSWRp4boKgycvLSgNBMx7scTuBqftW/YRPJMcCsPDr6eh26NbttlYa0HwsL5oNnAXFJE/V19JCozcYOL6zNhLY1SHM1waNYTmdc84edpLMHWd0IMvUteOTkZg5jrXebB/eHgS2crzgy/l/TGdb1SNqfVSoHYHxTOt7uWqKYjF8ZaAQdEX7xBY4LAOB+JB0fJTJqOr9osG66HCEH25quQFsR0o4WhrH53GywzcglTyU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
