travis:
  secure:
    BINSTAR_TOKEN: ncoAxejTpovmqUrr1trdHa0gq53O7CBzGTqmMy0EoXCdjJmm5c/dJ4f4sn1l4w1uXbeOPsG6UG60tTuZbSlug/dn4tNFQkNvIhFHi9I53XwaGivXmUpCs+g9nTPZKJDEkWk0jos0c6DYewZ0TjLS0U7nTKKWWEN4G30otx+og0fbsauH8Ss3vH9nlMgbYihxz5ouhUOQ4GUA8pax6O8CzvB4fgm1G1jE+DqVkjyGs+8g6qn529TmkhmirFcAX6CBhiq4+mQnwt80Xa+DWQGHDqg2sHXrBwzsP1PVkreBx+KUAS7G8aqsZiGo0fKhxXzceBBi/s3xeyxly+UcVBpZwpsTPZ/HkWIGP18FFTYeJ5YgtLTy2HnpunJx126iyz7MHh6IhVLZQ3lON4rwvfaguZjPoqgqiDUSHeDq5fLI5uSXmnFLQIgNqhIrtdmWvdDt7tJmpitJ6ElHAWCKHcyDB4c/EjxKGDuYpnWJLAi70PNWB7XErdGpTe9iu5/MjwPZ8UmYB0+cOlKC/Q91En9kVzWzI41l9Yn0oyF4lZNHqe0dNAUuHAu0F1k98VoD7co+6gz5quSpwEaHh9r9YamTkO6jFbNsi64DjR3HX7anxP4if/E2TMOflyfHvSGQfpa2hrAzgvFGlWWDYyrXnPiWKIQc2Kg5tZULlHbyhZVyKGk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
